### ISSUE TITLE
@import statements use static links

### ISSUE THREAD

**Issue by BH-DexterLeBlancJr** [PredixDev/px-starter-kit-design#3] opened 2017-07-26 15:20 UTC
Hi,

First of all thank you very much for your efforts, they are appreciated.

I'm using an angular-cli project(webpack, angular2, SCSS).  When installing the kit I get build errors as the @import statements are static instead of relative:

@import 'px-functions-design/_tools.functions.scss' // looking in the root of the project
vs
@import '../px-functions-design/_tools.functions.scss' // looking in the bower_components directory

To reproduce:
1. install angular-cli -> npm install -g @angular/cli@latest
2. create a project -> ng new my_app --style=scss
3. change to project directory -> cd my_app
4. install npm packages -> npm install
5. build app -> npm run build
6. set bower_components directory in the .bowerrc file-> 
{
  "directory" : "src/assets/bower_components"
}

6. install px-starter-kit-design -> bower install  px-starter-kit-design
7. Add packages to src/styles.scss file ->

// begin code ////////////////////////////////////////////////////////////////////////////////////////////////////////
// Settings
@import "/assets/bower_components/px-colors-design/_settings.colors.scss";

// Tools

// Generic
@import "/assets/bower_components/px-normalize-design/_generic.normalize.scss";
@import "/assets/bower_components/px-box-sizing-design/_generic.box-sizing.scss";
@import "assets/bower_components/px-helpers-design/_generic.helpers.scss";

// Base
@import "/assets/bower_components/px-flexbox-design/_base.flexbox.scss";
@import "/assets/bower_components/px-viewport-design/_base.viewport.scss";
@import "/assets/bower_components/px-typography-design/_base.typography.scss";

// Meta

// Objects

// Component
// Your css goes in here

// Trumps
@import "/assets/bower_components/inuit-clearfix/_trumps.clearfix.scss";
@import "/assets/bower_components/px-spacing-responsive-design/_trumps.spacing-responsive.scss";
@import "/assets/bower_components/px-widths-responsive-design/_trumps.widths-responsive.scss";

// end code //////////////////////////////////////////////////////////////////////////////////////////////////////////

8. build app -> npm run build

Thank you,
Dxtr

**Comment by randyaskin** [comment] 2017-07-26 15:45
We use the [node-sass-import-once module](https://github.com/at-import/node-sass-import-once) in our [gulp task](https://github.com/PredixDev/px-starter-kit-design/blob/master/gulpfile.js#L17-L23), which automatically resolves these paths for us, and prevents any duplication or circular dependency issues within our css modules and components. Can you try adding that module to your build process? It will automatically pick up the path to your bower_components folder from .bowerrc.

**Comment by santosh2686** [comment] 2017-08-02 23:48
I am using Webpack and it is not resolving the path for the SASS files which are not on the same path. Here are the screenshots for the same.
I think it is alway good to fix the root caused.

<img width="919" alt="screen shot 2017-08-02 at 4 45 12 pm" src="https://user-images.githubusercontent.com/6681311/28899892-3fa78b3a-77a2-11e7-896c-09942a93e7ae.png">

<img width="488" alt="screen shot 2017-08-02 at 4 44 48 pm" src="https://user-images.githubusercontent.com/6681311/28899901-47738d14-77a2-11e7-9fbb-d9a550bf2998.png">

Here is the screen sheet after fixing the issue

<img width="555" alt="screen shot 2017-08-02 at 4 49 17 pm" src="https://user-images.githubusercontent.com/6681311/28899983-c2a6b4fc-77a2-11e7-9fc7-66e997c94f1c.png">

**Comment by mdwragg** [comment] 2017-08-02 23:55
Yeah, I'm not following @santosh2686 - what's the issue? What is the 'after the fix'?

**Comment by randyaskin** [comment] 2017-08-03 17:20
We can't guarantee that all projects will be using the same directory structure and, as I stated in my earlier answer, import-once is important due to the complexity of how our design libraries hang together. I did a quick Google search and there is plenty of information available on using node-sass-import-once with webpack, e.g. https://www.npmjs.com/package/sass-loader-once - that is our recommended approach.

**Comment by CarrierDirectJack** [comment] 2018-04-12 21:46
If anyone's still having issues with this in Webpack 4-land, this seems to do the trick:

```
      {
        test: /\.scss$/,
        use: [
          ...
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['node_modules', 'bower_components'],
            },
          },
        ],
      },
```

**Closed as completed** 2019-02-25 02:26 UTC
Labels: wontfix
